/**
 * Generates `src/config/openapi.generated.ts` from the `@swagger` JSDoc blocks.
 *
 * swagger-jsdoc globs TypeScript sources at call time. That works locally but
 * not in a serverless deployment (Vercel), where only the compiled `dist`
 * output ships — the glob matches nothing and the served spec has zero paths.
 * Baking the document into a plain module at build time removes the runtime
 * filesystem dependency entirely and keeps the file traceable as a static
 * import, so the bundler always includes it.
 *
 * Run via `pnpm openapi:generate` (also wired into `pnpm build`).
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import swaggerJSDoc from 'swagger-jsdoc';
import { swaggerOptions } from '../src/config/swagger.options';

const outputFile = path.resolve(__dirname, '../src/config/openapi.generated.ts');

const spec = swaggerJSDoc(swaggerOptions) as { paths?: Record<string, unknown> };
const pathCount = Object.keys(spec.paths ?? {}).length;

if (pathCount === 0) {
  console.error(
    `No operations found for globs: ${JSON.stringify(swaggerOptions.apis)}\n` +
      `Run this from the backend/ directory so the globs resolve.`
  );
  process.exit(1);
}

const contents = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-openapi.ts — do not edit by hand.
// Regenerate with: pnpm openapi:generate
import type { OpenApiDocument } from './openapi.types';

export const openapiDocument: OpenApiDocument = ${JSON.stringify(spec, null, 2)};
`;

writeFileSync(outputFile, contents, 'utf8');
console.log(`Wrote ${pathCount} documented paths to ${path.relative(process.cwd(), outputFile)}`);
