/* eslint-disable */
// AUTO-GENERATED by scripts/generate-openapi.ts — do not edit by hand.
// Regenerate with: pnpm openapi:generate
import type { OpenApiDocument } from './openapi.types';

export const openapiDocument: OpenApiDocument = {
  "openapi": "3.0.0",
  "info": {
    "title": "Care-Queue API",
    "version": "1.0.0",
    "description": "API documentation for Care-Queue Backend (Phase 1)"
  },
  "servers": [
    {
      "url": "/api",
      "description": "Current host"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/visits": {
      "post": {
        "summary": "Create a new visit (links appointment, check-in, queue entry)",
        "tags": [
          "Visits"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "patientId"
                ],
                "properties": {
                  "patientId": {
                    "type": "string"
                  },
                  "practitionerId": {
                    "type": "string"
                  },
                  "departmentId": {
                    "type": "string"
                  },
                  "serviceId": {
                    "type": "string"
                  },
                  "locationId": {
                    "type": "string"
                  },
                  "appointmentId": {
                    "type": "string"
                  },
                  "checkInId": {
                    "type": "string"
                  },
                  "queueEntryId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Visit created"
          }
        }
      },
      "get": {
        "summary": "List visits for this organization (with filters)",
        "tags": [
          "Visits"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "in": "query",
            "name": "patientId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "practitionerId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of visits"
          }
        }
      }
    },
    "/visits/{id}": {
      "get": {
        "summary": "Get visit details by ID",
        "tags": [
          "Visits"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Visit data"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/visits/{id}/status": {
      "patch": {
        "summary": "Update visit status (state machine enforced)",
        "tags": [
          "Visits"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "status"
                ],
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "ARRIVED",
                      "IN_PROGRESS",
                      "COMPLETED",
                      "CANCELLED"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Visit updated"
          },
          "400": {
            "description": "Invalid state transition"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "List users",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: PLATFORM_ADMIN (all users), ORG_ADMIN (own org users only)\n",
        "responses": {
          "200": {
            "description": "List of users"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "summary": "Create / invite a new staff user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: PLATFORM_ADMIN, ORG_ADMIN\nRole escalation is prevented — ORG_ADMIN cannot assign PLATFORM_ADMIN role.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "password",
                  "role"
                ],
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8
                  },
                  "phone": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "ORG_ADMIN",
                      "RECEPTIONIST",
                      "PRACTITIONER",
                      "STAFF",
                      "PATIENT"
                    ]
                  },
                  "organizationId": {
                    "type": "string",
                    "description": "PLATFORM_ADMIN only — defaults to caller's org"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created"
          },
          "400": {
            "description": "Validation error"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get user by ID",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update user profile or role",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated user"
          },
          "403": {
            "description": "Forbidden or role escalation attempted"
          }
        }
      },
      "delete": {
        "summary": "Deactivate user (soft-delete)",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User deactivated"
          }
        }
      }
    },
    "/services": {
      "get": {
        "summary": "List active services for this organization",
        "tags": [
          "Services"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "departmentId",
            "schema": {
              "type": "string"
            },
            "description": "Filter by department"
          }
        ],
        "responses": {
          "200": {
            "description": "List of services"
          }
        }
      },
      "post": {
        "summary": "Create a service (ORG_ADMIN only)",
        "tags": [
          "Services"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "departmentId"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "New Patient Consultation"
                  },
                  "departmentId": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "durationInMinutes": {
                    "type": "integer",
                    "default": 15
                  },
                  "price": {
                    "type": "number"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Service created"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/services/{id}": {
      "get": {
        "summary": "Get service by ID",
        "tags": [
          "Services"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Service data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update service (ORG_ADMIN only)",
        "tags": [
          "Services"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Deactivate service (ORG_ADMIN only)",
        "tags": [
          "Services"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deactivated"
          }
        }
      }
    },
    "/schedules/availability": {
      "get": {
        "summary": "Get available appointment slots for a practitioner on a date",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "practitionerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "date",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            },
            "description": "Date in YYYY-MM-DD format"
          },
          {
            "in": "query",
            "name": "slotDurationMin",
            "schema": {
              "type": "integer",
              "default": 15
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of available { start, end } slots"
          }
        }
      }
    },
    "/schedules": {
      "get": {
        "summary": "List recurring schedules",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "summary": "Create a recurring schedule for a practitioner",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/schedules/practitioner/{practitionerId}": {
      "get": {
        "summary": "Get full schedule + exceptions for a practitioner",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/schedules/{id}": {
      "put": {
        "summary": "Update a schedule",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "delete": {
        "summary": "Deactivate a schedule",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/schedules/exceptions": {
      "get": {
        "summary": "List schedule exceptions (leave / special days)",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "summary": "Create a schedule exception (e.g. doctor on leave)",
        "tags": [
          "Schedules"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "practitionerId",
                  "date",
                  "reason",
                  "isAvailable"
                ],
                "properties": {
                  "practitionerId": {
                    "type": "string"
                  },
                  "date": {
                    "type": "string",
                    "format": "date"
                  },
                  "reason": {
                    "type": "string"
                  },
                  "isAvailable": {
                    "type": "boolean"
                  },
                  "startTime": {
                    "type": "string",
                    "example": "09:00"
                  },
                  "endTime": {
                    "type": "string",
                    "example": "13:00"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/queues": {
      "get": {
        "summary": "List active queues for this organization",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "in": "query",
            "name": "departmentId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "practitionerId",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of queues"
          }
        }
      },
      "post": {
        "summary": "Create a new queue",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "departmentId": {
                    "type": "string"
                  },
                  "locationId": {
                    "type": "string"
                  },
                  "practitionerId:{ type": "string }",
                  "serviceId": {
                    "type": "string"
                  },
                  "queueDate": {
                    "type": "string",
                    "format": "date"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Queue created"
          }
        }
      }
    },
    "/queues/{queueId}/entries": {
      "get": {
        "summary": "List all entries in a queue (with position + ETA)",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "queueId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Queue entries with position and ETA"
          }
        }
      }
    },
    "/queues/{queueId}/call-next": {
      "post": {
        "summary": "Call the next highest-priority waiting patient",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "queueId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Queue entry moved to IN_CONSULTATION"
          }
        }
      }
    },
    "/queues/join": {
      "post": {
        "summary": "Add a patient to a queue",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "queueId",
                  "patientId"
                ],
                "properties": {
                  "queueId": {
                    "type": "string"
                  },
                  "patientId": {
                    "type": "string"
                  },
                  "appointmentId": {
                    "type": "string"
                  },
                  "checkInId": {
                    "type": "string"
                  },
                  "priority": {
                    "type": "string",
                    "enum": [
                      "NORMAL",
                      "HIGH",
                      "EMERGENCY"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully joined the queue"
          },
          "409": {
            "description": "Patient already waiting in this queue"
          }
        }
      }
    },
    "/queues/entry/{entryId}/recall": {
      "post": {
        "summary": "Recall a waiting or skipped patient",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "entryId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Patient recalled"
          }
        }
      }
    },
    "/queues/entry/{entryId}/status": {
      "put": {
        "summary": "Update queue entry status (state machine enforced)",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "entryId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "status"
                ],
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "IN_CONSULTATION",
                      "COMPLETED",
                      "SKIPPED",
                      "NO_SHOW",
                      "CANCELLED",
                      "WAITING"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Queue entry updated"
          },
          "400": {
            "description": "Invalid state transition"
          }
        }
      }
    },
    "/queues/entry/{entryId}/position": {
      "get": {
        "summary": "Get live position and ETA for a patient (mobile polling endpoint)",
        "tags": [
          "Queues"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "entryId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Position and estimated wait"
          }
        }
      }
    },
    "/practitioners": {
      "get": {
        "summary": "List all practitioners for this organization",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "type",
            "schema": {
              "type": "string",
              "enum": [
                "DOCTOR",
                "DENTIST",
                "PHYSIOTHERAPIST",
                "PSYCHOLOGIST",
                "OTHER"
              ]
            },
            "description": "Filter by practitioner type"
          }
        ],
        "responses": {
          "200": {
            "description": "List of practitioners"
          }
        }
      },
      "post": {
        "summary": "Create a practitioner profile (ORG_ADMIN only)",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "type"
                ],
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "DOCTOR",
                      "DENTIST",
                      "PHYSIOTHERAPIST",
                      "PSYCHOLOGIST",
                      "OTHER"
                    ]
                  },
                  "specializations": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "contactEmail": {
                    "type": "string"
                  },
                  "contactPhone": {
                    "type": "string"
                  },
                  "userId": {
                    "type": "string",
                    "description": "Optional — link to a PRACTITIONER user account"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Practitioner created"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/practitioners/{id}": {
      "get": {
        "summary": "Get practitioner by ID",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Practitioner data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update practitioner profile (ORG_ADMIN only)",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Deactivate practitioner (ORG_ADMIN only)",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deactivated"
          }
        }
      }
    },
    "/practitioners/{id}/departments": {
      "get": {
        "summary": "List departments this practitioner belongs to",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "summary": "Assign practitioner to a department (with optional services)",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/practitioners/{id}/departments/{deptId}": {
      "delete": {
        "summary": "Remove practitioner from a department",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/practitioners/by-department/{deptId}": {
      "get": {
        "summary": "List all practitioners in a department",
        "tags": [
          "Practitioners"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/patients": {
      "post": {
        "summary": "Register a patient profile",
        "tags": [
          "Patients"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "mobileNumber"
                ],
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "mobileNumber": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  },
                  "gender": {
                    "type": "string",
                    "enum": [
                      "MALE",
                      "FEMALE",
                      "OTHER",
                      "PREFER_NOT_TO_SAY"
                    ]
                  },
                  "email": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  },
                  "emergencyContact": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Patient registered successfully"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "get": {
        "summary": "Get all patients for the organization",
        "tags": [
          "Patients"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of patients"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/patients/{id}": {
      "get": {
        "summary": "Get patient by ID",
        "tags": [
          "Patients"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Patient data"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Patient not found"
          }
        }
      }
    },
    "/organizations": {
      "post": {
        "summary": "Create a new organization (PLATFORM_ADMIN only)",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: PLATFORM_ADMIN only.\nCreates a new tenant. The created organization is then assigned\nan ORG_ADMIN via the Users API.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "type",
                  "contactEmail"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "ABC Multispeciality Hospital"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "HOSPITAL",
                      "CLINIC",
                      "PRIVATE_PRACTICE",
                      "DIAGNOSTIC_CENTER",
                      "HEALTHCARE_CENTER"
                    ]
                  },
                  "contactEmail": {
                    "type": "string"
                  },
                  "contactPhone": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Organization created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden — PLATFORM_ADMIN only"
          }
        }
      },
      "get": {
        "summary": "List all organizations (PLATFORM_ADMIN only)",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of all organizations"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/locations": {
      "get": {
        "summary": "List all active locations for this organization",
        "tags": [
          "Locations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of locations"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "post": {
        "summary": "Create a new location / branch",
        "tags": [
          "Locations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: ORG_ADMIN, PLATFORM_ADMIN only.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "type"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Main Campus"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "MAIN_CAMPUS",
                      "BRANCH",
                      "EMERGENCY_CENTER",
                      "SATELLITE"
                    ],
                    "example": "MAIN_CAMPUS"
                  },
                  "address": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "contactEmail": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Location created"
          },
          "400": {
            "description": "Validation error"
          },
          "403": {
            "description": "Forbidden — insufficient role"
          }
        }
      }
    },
    "/locations/{id}": {
      "get": {
        "summary": "Get location by ID",
        "tags": [
          "Locations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Location data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update location",
        "tags": [
          "Locations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated location"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "delete": {
        "summary": "Deactivate (soft-delete) a location",
        "tags": [
          "Locations"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Location deactivated"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/departments": {
      "get": {
        "summary": "List all departments for this organization",
        "tags": [
          "Departments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of departments"
          }
        }
      },
      "post": {
        "summary": "Create a department (ORG_ADMIN only)",
        "tags": [
          "Departments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Cardiology"
                  },
                  "description": {
                    "type": "string"
                  },
                  "locationId": {
                    "type": "string",
                    "description": "Optional — leave blank if cross-location"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Department created"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/departments/{id}": {
      "get": {
        "summary": "Get department by ID",
        "tags": [
          "Departments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Department data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "put": {
        "summary": "Update department (ORG_ADMIN only)",
        "tags": [
          "Departments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Deactivate department (ORG_ADMIN only)",
        "tags": [
          "Departments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deactivated"
          }
        }
      }
    },
    "/check-ins": {
      "get": {
        "summary": "List today's check-ins for this organization",
        "tags": [
          "Check-Ins"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: RECEPTIONIST, ORG_ADMIN, PRACTITIONER, PLATFORM_ADMIN\n",
        "responses": {
          "200": {
            "description": "List of today's check-ins"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      },
      "post": {
        "summary": "Create a patient check-in (or walk-in)",
        "tags": [
          "Check-Ins"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "RBAC: RECEPTIONIST, ORG_ADMIN, PLATFORM_ADMIN, PATIENT (self check-in via mobile)\n\nWalk-in flow (docs §18): omit appointmentId. The system will create the\ncheck-in without an associated appointment.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "patientId"
                ],
                "properties": {
                  "patientId": {
                    "type": "string"
                  },
                  "appointmentId": {
                    "type": "string",
                    "description": "Optional — omit for walk-in"
                  },
                  "locationId": {
                    "type": "string"
                  },
                  "source": {
                    "type": "string",
                    "enum": [
                      "RECEPTION",
                      "KIOSK",
                      "MOBILE"
                    ],
                    "default": "RECEPTION"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Check-in created"
          },
          "400": {
            "description": "Validation error"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/check-ins/{id}": {
      "get": {
        "summary": "Get check-in by ID",
        "tags": [
          "Check-Ins"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Check-in data"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Register a new user",
        "description": "Creates a user with a role. Role must be one of:\nPLATFORM_ADMIN | ORG_ADMIN | RECEPTIONIST | PRACTITIONER | STAFF | PATIENT\n\nWhen organizationId is provided the user is scoped to that tenant.\nAll subsequent requests by this user will be automatically filtered\nto that organization (tenant isolation).\n",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "password"
                ],
                "properties": {
                  "firstName": {
                    "type": "string",
                    "example": "Rahul"
                  },
                  "lastName": {
                    "type": "string",
                    "example": "Patel"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8
                  },
                  "phone": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "PLATFORM_ADMIN",
                      "ORG_ADMIN",
                      "RECEPTIONIST",
                      "PRACTITIONER",
                      "STAFF",
                      "PATIENT"
                    ],
                    "default": "PATIENT"
                  },
                  "organizationId": {
                    "type": "string",
                    "description": "Required for org-scoped roles"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User registered — returns user object and JWT token"
          },
          "400": {
            "description": "Validation error or email already exists"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "description": "Returns a JWT token containing id, role, and organizationId.\nUse this token as `Authorization: Bearer <token>` on all protected routes.\n",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful — returns JWT token"
          },
          "401": {
            "description": "Invalid credentials"
          }
        }
      }
    },
    "/auth/me": {
      "get": {
        "summary": "Get current authenticated user profile",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Authenticated user profile"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/appointments": {
      "post": {
        "summary": "Book a new appointment",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "patientId",
                  "date"
                ],
                "properties": {
                  "patientId": {
                    "type": "string"
                  },
                  "practitionerId": {
                    "type": "string"
                  },
                  "departmentId": {
                    "type": "string"
                  },
                  "serviceId": {
                    "type": "string"
                  },
                  "locationId": {
                    "type": "string"
                  },
                  "date": {
                    "type": "string",
                    "format": "date"
                  },
                  "scheduledStartTime": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "scheduledEndTime": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "source": {
                    "type": "string",
                    "enum": [
                      "ONLINE",
                      "WALK_IN",
                      "PHONE",
                      "RECEPTION",
                      "REFERRAL"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Appointment booked"
          }
        }
      },
      "get": {
        "summary": "List all appointments (staff/admin view with filters)",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date"
            }
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "practitionerId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "departmentId",
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "patientId",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of appointments"
          }
        }
      }
    },
    "/appointments/mine": {
      "get": {
        "summary": "Get the authenticated patient's own appointments",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of appointments"
          }
        }
      }
    },
    "/appointments/practitioner/{practitionerId}": {
      "get": {
        "summary": "Get appointments for a specific practitioner",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "practitionerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of practitioner appointments"
          }
        }
      }
    },
    "/appointments/{id}": {
      "get": {
        "summary": "Get a single appointment by ID",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Appointment data"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "delete": {
        "summary": "Cancel an appointment (soft cancel via state machine)",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Appointment cancelled"
          },
          "400": {
            "description": "Cannot cancel in current state"
          }
        }
      }
    },
    "/appointments/{id}/status": {
      "patch": {
        "summary": "Update appointment status (state machine enforced)",
        "tags": [
          "Appointments"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "status"
                ],
                "properties": {
                  "status": {
                    "type": "string",
                    "enum": [
                      "CONFIRMED",
                      "CHECKED_IN",
                      "IN_QUEUE",
                      "IN_CONSULTATION",
                      "COMPLETED",
                      "CANCELLED",
                      "NO_SHOW",
                      "RESCHEDULED"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Status updated"
          },
          "400": {
            "description": "Invalid state transition"
          }
        }
      }
    },
    "/analytics/overview": {
      "get": {
        "summary": "Dashboard overview — today's appointments, queue, check-ins, visits",
        "tags": [
          "Analytics"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Operational dashboard metrics"
          }
        }
      }
    },
    "/analytics/queue-performance": {
      "get": {
        "summary": "Queue performance metrics over the past N days",
        "tags": [
          "Analytics"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "days",
            "schema": {
              "type": "integer",
              "default": 7
            },
            "description": "Number of past days to include (default 7)"
          }
        ],
        "responses": {
          "200": {
            "description": "Average wait time, consultation time, no-show rate"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Visits",
      "description": "Visit/Encounter lifecycle — the central operational record"
    },
    {
      "name": "Users",
      "description": "Staff user management (docs §13).\nPLATFORM_ADMIN manages all users across all tenants.\nORG_ADMIN manages only users within their own organization.\n\nRoles: PLATFORM_ADMIN | ORG_ADMIN | RECEPTIONIST | PRACTITIONER | STAFF | PATIENT\n"
    },
    {
      "name": "Services",
      "description": "Clinical services that patients book (docs §9).\nExamples: \"New Patient Consultation\", \"Follow-up\", \"ECG\", \"Physiotherapy Session\".\nServices are linked to a department and have a duration and optional price.\n"
    },
    {
      "name": "Schedules",
      "description": "Practitioner scheduling and availability"
    },
    {
      "name": "Queues",
      "description": "Queue management and patient flow"
    },
    {
      "name": "Practitioners",
      "description": "Practitioner management (docs §10).\nTypes per docs: DOCTOR | DENTIST | PHYSIOTHERAPIST | PSYCHOLOGIST | OTHER.\nA practitioner profile is separate from the User identity per docs rule §13 / §23.\n"
    },
    {
      "name": "Organizations",
      "description": "Multi-tenant organization (tenant) management (docs §3).\nEach organization represents one healthcare customer —\na hospital, clinic, private practice, or diagnostic center.\n\nOrganization types:\n  HOSPITAL | CLINIC | PRIVATE_PRACTICE | DIAGNOSTIC_CENTER | HEALTHCARE_CENTER\n"
    },
    {
      "name": "Locations",
      "description": "Hospital/clinic branch management (docs §7).\nAll results are automatically scoped to the authenticated user's organization.\n"
    },
    {
      "name": "Departments",
      "description": "Clinical department management (docs §8).\nDepartments can span multiple locations and contain multiple services.\n"
    },
    {
      "name": "Check-Ins",
      "description": "Patient arrival/check-in management (docs §16).\n\nA check-in is a DISTINCT OPERATIONAL EVENT from the appointment.\nIt captures the actual patient arrival time, which enables:\n- Waiting-time calculation\n- Late-arrival analysis\n- No-show analysis\n- Queue performance measurement\n\nWalk-ins are supported: simply omit appointmentId.\n"
    },
    {
      "name": "Auth",
      "description": "Authentication and session management"
    },
    {
      "name": "Appointments",
      "description": "Appointment booking and management"
    },
    {
      "name": "Analytics",
      "description": "Operational metrics and performance data"
    }
  ]
};
